# Generated by Django 3.1.6 on 2021-02-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='questname',
            field=models.CharField(max_length=255, verbose_name='Quest Name'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='rank',
            field=models.CharField(max_length=255, verbose_name='Quest Rank'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='target',
            field=models.CharField(max_length=255, verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weapon',
            field=models.CharField(choices=[('GS', 'Greate Sword'), ('LS', 'Long Sword'), ('SNS', 'Sword & Shiled'), ('db', 'Dual Blades'), ('HM', 'Hammer'), ('HH', 'Hunting Horn'), ('LN', 'Lance'), ('gl', 'Gunlance'), ('SA', 'Switch Axe'), ('CB', 'Charge Blade'), ('IG', 'Insect Glaive'), ('lbg', 'Light Bowgun'), ('HBG', 'Heavy Bowgun'), ('BOW', 'Bow'), ('MIX', 'Mixed')], max_length=255, verbose_name='Weapon'),
        ),
    ]
