# Generated by Django 3.1.6 on 2021-02-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210219_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='link',
            field=models.URLField(default='https://qiita.com/naoyeah/items/f1d9d1ebac02f3b7eb5a', max_length=2047),
        ),
        migrations.AlterField(
            model_name='record',
            name='rules',
            field=models.CharField(choices=[('FR', 'FreeStyle'), ('TW', 'TA wiki'), ('PD', 'Production')], max_length=255, verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weapon',
            field=models.CharField(choices=[('GS', 'Greate Sword'), ('LS', 'Long Sword'), ('SNS', 'Sword & Shiled'), ('DB', 'Dual Blades'), ('HM', 'Hammer'), ('HH', 'Hunting Horn'), ('LN', 'Lance'), ('GL', 'Gunlance'), ('SA', 'Switch Axe'), ('CB', 'Charge Blade'), ('IG', 'Insect Glaive'), ('LBG', 'Light Bowgun'), ('HBG', 'Heavy Bowgun'), ('BOW', 'Bow'), ('MIX', 'Mixed')], max_length=255, verbose_name='Weapon'),
        ),
    ]
