# Generated by Django 3.1.6 on 2021-02-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210227_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='imagpath',
            new_name='imagepath',
        ),
    ]
