# Generated by Django 3.1.6 on 2021-02-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210227_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Target Order')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.monster')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.quest')),
            ],
        ),
    ]
