# Generated by Django 3.1.6 on 2021-02-27 03:53

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_targetorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='monsters',
        ),
        migrations.AddField(
            model_name='quest',
            name='imagepath',
            field=cms.models.ListField(default=[''], verbose_name=models.CharField(max_length=1023, verbose_name='ImagePath')),
        ),
        migrations.DeleteModel(
            name='TargetOrder',
        ),
    ]
