# Generated by Django 3.1.6 on 2021-02-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210227_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='target',
            field=models.CharField(max_length=255, verbose_name='Quest Rank'),
        ),
    ]
