# Generated by Django 3.1.6 on 2021-02-28 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210228_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Priority in quest page'),
        ),
        migrations.AddField(
            model_name='quest',
            name='questname_j',
            field=models.CharField(default='日本語名', max_length=255, verbose_name='Quest Name japanese'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='cms.target', verbose_name='Target'),
        ),
    ]
