# Generated by Django 3.1.6 on 2021-02-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20210228_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='questname_j',
            field=models.CharField(max_length=255, verbose_name='Quest Name japanese'),
        ),
    ]
