# Generated by Django 3.1.6 on 2021-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20210228_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='recordnum',
            field=models.IntegerField(default=0, verbose_name='Number of record of this quest'),
        ),
    ]
