# Generated by Django 3.1.6 on 2021-03-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20210301_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=True, verbose_name='open')),
                ('status', models.CharField(choices=[('O', 'open'), ('C', 'close')], max_length=10, verbose_name='status')),
                ('request', models.CharField(choices=[('M', 'modify'), ('D', 'delete')], max_length=10, verbose_name='request')),
                ('reason', models.CharField(choices=[('C/B', 'cheat/bug'), ('M', 'miss input'), ('AR', 'against rule'), ('O', 'other')], max_length=10, verbose_name='reason')),
                ('detail', models.TextField(blank=True, max_length=1000, null=True, verbose_name='issue detail')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='cms.record', verbose_name='Record')),
            ],
        ),
    ]
