# Generated by Django 3.1.6 on 2021-03-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
    ]
