# Generated by Django 3.1.6 on 2021-03-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20210303_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='regist_date',
        ),
    ]
