# Generated by Django 3.1.6 on 2021-03-03 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_remove_record_regist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='link',
            field=models.URLField(error_messages={'invalid': 'invalid', 'required': 'aa'}, help_text='A Video from Youtube, niconico, bilibili is available.', max_length=2047, validators=[django.core.validators.RegexValidator(message='aaaaaaaaaaaa!!!', regex='^https://www.youtube.com/watch|https://www.nicovideo.jp/watch/|https://www.bilibili.com/video/')]),
        ),
    ]
