# Generated by Django 3.1.6 on 2021-03-03 14:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20210303_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='regist_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='record',
            name='link',
            field=models.URLField(error_messages={'invalid': 'invalid', 'required': 'aa'}, help_text='A Video from Youtube, niconico, bilibili is available.', max_length=2047, unique=True, validators=[django.core.validators.RegexValidator(message='aaaaaaaaaaaa!!!', regex='^https://www.youtube.com/watch|https://www.nicovideo.jp/watch/|https://www.bilibili.com/video/')]),
        ),
    ]
