# Generated by Django 3.1.6 on 2021-03-11 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0020_record_ipaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='record_submitter'),
        ),
    ]
